version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: abin
      POSTGRES_PASSWORD: Abin@123
      POSTGRES_DB: tweet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: abin@reontel.com
      PGADMIN_DEFAULT_PASSWORD: Abin@123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
